package com.co2plant.rtc.webrtc;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
import lombok.Getter;
import org.kurento.client.IceCandidate;
import org.kurento.client.WebRtcEndpoint;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.socket.TextMessage;
import org.springframework.web.socket.WebSocketSession;

import java.io.IOException;

public class UserSession {

    private final Logger log = LoggerFactory.getLogger(UserSession.class);
    private final ObjectMapper mapper = new ObjectMapper();

    @Getter
    private final String id;
    private final WebSocketSession session;

    @Getter
    private WebRtcEndpoint webRtcEndpoint;

    public UserSession(WebSocketSession session) {
        this.id = session.getId();
        this.session = session;
    }

    public void setWebRtcEndpoint(WebRtcEndpoint webRtcEndpoint) {
        this.webRtcEndpoint = webRtcEndpoint;

        // Add listener for ICE candidates generated by Kurento
        this.webRtcEndpoint.addIceCandidateFoundListener(event -> {
            IceCandidate candidate = event.getCandidate();
            // Send candidate to client
            ObjectNode response = mapper.createObjectNode();
            response.put("id", "iceCandidate");

            ObjectNode candidateJson = mapper.createObjectNode();
            candidateJson.put("candidate", candidate.getCandidate());
            candidateJson.put("sdpMid", candidate.getSdpMid());
            candidateJson.put("sdpMLineIndex", candidate.getSdpMLineIndex());
            response.set("candidate", candidateJson);

            sendMessage(response);
        });
    }

    public void sendMessage(ObjectNode message) {
        try {
            synchronized (session) {
                if (session.isOpen()) {
                    session.sendMessage(new TextMessage(message.toString()));
                }
            }
        } catch (IOException e) {
            log.error("Exception sending message", e);
        }
    }

    public void addCandidate(IceCandidate candidate) {
        if (this.webRtcEndpoint != null) {
            this.webRtcEndpoint.addIceCandidate(candidate);
        }
    }

    public void release() {
        if (this.webRtcEndpoint != null) {
            this.webRtcEndpoint.release();
        }
    }
}
